title: 小武的博客
description: 记录学习与思考
email: linxianwusx@gmail.com

# Your site's logo. Will be shown on the left top of your page.
logo: /img/logo.svg

# The RSS link of your blog.
rss: "/feed.xml"

# Theme Settings
theme_setting:
  # The nav links on the top right of home/page/post/blog layout.
  nav_pages:
    - "tags.md"
    - "about.md"
  # Enable code highlighting
  code: true
  mermaid: true

# Comment System Settings
comment:
  enabled: true
  provider: "gitalk"
  gitalk:
    clientID: "Ov23liaA7lwpJGXSuHyl"
    clientSecret: "068072d0fb5bed5d3100c3978a5edb8f77156877"
    repo: "xianwulin.github.io"
    owner: "XianwuLin"
    admin:
      - "XianwuLin"
    distractionFreeMode: false
    createIssueManually: false
